In [ ]:
%%capture
'''
Problem : 1
Here is a sample line of code that can be executed in Python:

print("Hello, World!")
You can just as easily store a string as a variable and then print it to stdout:

my_string = "Hello, World!"
print(my_string)
The above code will print Hello, World! on your screen. Try it yourself in the editor below!

Input Format

You do not need to read any input in this challenge.

Output Format

Print Hello, World! to stdout.

Sample Output 0

Hello, World!
'''

In [ ]:
print("Hello, World!")

In [ ]:
%%capture
'''
prob 2
https://www.hackerrank.com/challenges/py-if-else/problem?isFullScreen=

Given an integer, n , perform the following conditional actions:

If n is odd, print Weird
If n is even and in the inclusive range of 2 to 5 , print Not Weird
If n is even and in the inclusive range of 6 to 20 , print Weird
If n is even and greater than 20, print Not Weird
Input Format

A single line containing a positive integer, n.

Constraints

1<=n<=100

Output Format

Print Weird if the number is weird. Otherwise, print Not Weird.

Sample Input 0

3

Sample Output 0

Weird

Explanation 0

n = 3

n is odd and odd numbers are weird, so print Weird.

Sample Input 1

24
Sample Output 1

Not Weird
Explanation 1

n = 24
n>20 and n is even, so it is not weird.
'''

In [ ]:
n = int(input())
if n%2 != 0:
    print("Weird")
if n%2 == 0 and n >2 and n<5:
    print("Not Weird")
if n%2 == 0 and n>6 and n < 21:
    print("Weird")
if n%2 == 0 and n > 20:
    print("Not Weird")

In [ ]:
%%capture
'''
problem 3
The provided code stub reads two integers from STDIN,  and . Add code to print three lines where:

1.The first line contains the sum of the two numbers.
2.The second line contains the difference of the two numbers (first - second).
3.The third line contains the product of the two numbers.
Example
a = 3
b = 5
Print the following:
8
-2
15
Input Format
The first line contains the first integer, a.
The second line contains the second integer, b.

Constraints
1<=a<=10**10
1<=b<=10**10

Output Format

Print the three lines as explained above.

Sample Input 0

3
2
Sample Output 0

5
1
6
Explanation 0
3+2==>5
3-2 == >1
3*2==>6
'''

In [ ]:
a = int(input())
b = int(input())

print(a+b)
print(a-b)
print(a*b)

In [ ]:
%%capture
''' problem-4
The provided code stub reads two integers, a and b , from STDIN.

Add logic to print two lines. The first line should contain the result of integer division,  a//b . The second line should contain the result of float division,  a/b .

No rounding or formatting is necessary.

Example
a=3
b=5

The result of the integer division 3//5 = 0.
The result of the float division is 3/5 = 0.6.
Print:
0
0.6
Input Format

The first line contains the first integer, a.
The second line contains the second integer, b.

Output Format

Print the two lines as described above.

Sample Input 0

4
3
Sample Output 0

1
1.33333333333
'''

In [ ]:
a = int(input())
b = int(input())

print(a//b)
print(a/b)

In [ ]:
%%capture
'''Task:
problem 4
      The provided code stub reads and integer, n  , from STDIN. For all non-negative integers i<n, print i^2.

Example:
       n=3
       The list of non-negative integers that are less than  n=3 is [0,1,2] . Print the square of each number on a separate line.
      0
      1
      4


Input Format:
     The first and only line contains the integer, n.

Constraints:
     1<=n<=20

Output Format:
     Print  n lines, one corresponding to each i.

'''

In [ ]:
n = int(input())
if n in range (1,21):
    for i in range (0,n):
        print(i**2)
else:
    print("Check Constraints")

In [ ]:
%%capture
'''
Problem 5
An extra day is added to the calendar almost every four years as February 29, and the day is called a leap day. It corrects the calendar for the fact that our planet takes approximately 365.25 days to orbit the sun. A leap year contains a leap day.

In the Gregorian calendar, three conditions are used to identify leap years:

1.The year can be evenly divided by 4, is a leap year, unless:
     2.The year can be evenly divided by 100, it is NOT a leap year, unless:    
          3.The year is also evenly divisible by 400. Then it is a leap year.

This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years. Source


Task:
        Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.
        Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.


Input Format:
        Read year, the year to test.


Constraints:
        1900<=year<=10^5


Output Format:
        The function must return a Boolean value (True/False). Output is handled by the provided code stub.
'''

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range (0,n):
        print(i+1,end="")

## incorrect regex problem

In [ ]:
%%capture
'''
Problem - 6
You are given a string S.
Your task is to find out whether S is a valid regex or not.


Input Format

The first line contains integer T, the number of test cases.
The next T lines contains the string S.


Constraints
0<T<100


Output Format

Print "True" or "False" for each test case without quotes.
'''

In [ ]:
import re
cases = int(input())
for i in range(cases):
    try:
        re.compile(input())
        output = True
    except:
        output = False
    print(output)

## NUMPY

In [ ]:
%%capture
'''
problem 7
floor
The tool floor returns the floor of the input element-wise.
The floor of x is the largest integer i where i <= x.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
ceil
The tool ceil returns the ceiling of the input element-wise.
The ceiling of x is the smallest integer i where i => x.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
rint
The rint tool rounds to the nearest integer of input element-wise.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
Task
You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

Note
In order to get the correct output format, add the line numpy.set_printoptions(legacy=”1.13) below the numpy import.

Input Format
A single line of input containing the space separated elements of array A.

Output Format
On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.

Sample Input

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Sample Output

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
'''

https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?isFullScreen=true&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [ ]:
import numpy
numpy.set_printoptions(legacy="1.13")
a = input().split(" ")
a = [float(i) for i in a]

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))


In [1]:
%%capture
'''
Problem 8
Sum 
The sum tool returns the sum of array elements over a given axis. 
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10

By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.
 
Prod
The prod tool returns the product of array elements over a given axis.
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
 
By default, the axis value is None. Therefore, it performs the product over all the dimensions of the input array.
 
Task :
You are given a 2-D array with dimensions NXM.
Your task is to perform the sum tool over axis 0 and then find the product of that result. 


Input Format :
The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

Output Format :
Compute the sum along axis 0. Then, print the product of that sum.


Sample Input :
2 2
1 2
3 4
 
Sample Output :

24

Explanation :
The sum along axis 0 = [4 6]
The product of this sum = 24'''

In [ ]:
import numpy
N,M = input().split(" ")
N = int(N)
M = int(M)
l = []
m = []
for i in range(N):
    l.append(input())
    
for item in l:
    m.append(item.split(" "))
m = numpy.ravel(m)
m = numpy.array([int(x) for x in m])
m = m.reshape(N,M)
print(m.sum(0).prod())

In [ ]:
%%capture
'''
Problem 9
List Comprehensions

Let's learn about list comprehensions! You are given three integers X, Y and Z representing the dimensions of a cuboid along with an
integer N. You have to print a list of all possible coordinates given by (i, j, k) on a 3D grid where the sum of i + j + k  is not
equal to N. Here, 0 <= i <= X; 0 <= j <= Y; 0 <= k <= Z 

Input Format
Four integers X, Y, Z and N each on four separate lines, respectively.

Constraints
Print the list in lexicographic increasing order.

Sample Input
1
1
1
2

Sample Output
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

'''

In [ ]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    l = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k != n]
    print (l)

In [ ]:
%%capture
'''
Problem 10
Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given n scores. Store them in a list and find the score of the runner-up.


Input Format :
The first line contains n. The second line contains an array A[] of n integers each separated by a space.

Constraints :
2 <= n <= 10
-100 <= A[i] <= 100

Output Format :
Print the runner-up score.


Sample Input :
5
2 3 6 6 5

Sample Output :
5

Explanation :
Given list is [2,3,6,6,5]. The maximum score is 6, second maximum is 5. Hence, we print 5 as the runner-up score.'''

In [ ]:
if __name__ == '__main__':
    n = int(input())
    string = input().split(" ")
    string = [int(x) for x in string]
    string.sort()
    maximum = string[-1]
    l=[]
    for item in string:
        if item != maximum:
            l.append(item)
    print(l[-1])

In [ ]:
%%capture 
'''Problem 11
Given the names and grades for each student in a class
of N students, store them in a nested list and print the name(s) of any
student(s) having the second lowest grade.  
Note: If there are multiple students with the
second lowest grade, order their names alphabetically and print each name on a new
line. 
Example  records  = [[ “chi”, 20.0]], [“beta”, 50.0], [“alpha”, 50.0]  The
ordered list of scores is [20.0, 50.0], so the second lowest score is 50.0. There are
two students with that score: [“beta”, “alpha”]. Ordered alphabetically, the names
are printed as:   alpha beta Input Format The first line contains an integer, ,
the number of students. The  subsequent lines describe each student over  lines. 
The first line contains a student’s name. The second line contains their grade.
Constraints 2 <= N <= 5 There will always be one or more students having the second lowest
grade. Output Format Print the name(s) of any student(s) having the second lowest
grade in. If there are multiple students, order their names alphabetically and print
each one on a new line.  Sample Input 0  5 Harry 37.21 Berry 37.21 Tina 37.2 Akriti
41 Harsh 39 Sample Output 0  Berry Harry Explanation 0   There are 5 students in
this class whose names and grades are assembled to build the following list: 
python students = [[‘Harry’, 37.21], [‘Berry’, 37.21], [‘Tina’, 37.2], [‘Akriti’,
41], [‘Harsh’, 39]]  The lowest grade of 37.2 belongs to Tina. The second lowest
grade of 37.21 belongs to both Harry and Berry, so we order their names
alphabetically and print each name on a new line.'''

In [ ]:
if __name__ == '__main__':
    l1=[]
    l2=[]
    l3=[]
    result=[]
    for _ in range(int(input())):
        name = input()
        score = float(input())
        l1.append(name)
        l2.append(score)
    d = dict(zip(l1,l2))
    l2.sort()
    minimum = l2[0]
    for item in l2:
        if item != minimum:
            l3.append(item)
            
    for key,val in d.items():
        if val == l3[0]:
            result.append(key)
    result.sort()       
    for item in result:
        print(item)